### ISSUE TITLE
Determining AC Consensus of Post-Review Changes

### ISSUE THREAD

**Issue by fantasai** [w3c/process#825]
@tantek, @frivoal, and I discussed some of the ambiguities in the Process around what happens when we follow the "adopt with substantive changes" track in https://www.w3.org/Consortium/Process/Drafts/#ACReviewAfter and how to fix them. We think three changes are necessary (two to Process, one to Guide):

1. Objections that block consensus of substantive changes during the consensus check, like those during the AC Review itself, get registered as Formal Objections.
2. These Formal Objections get batch processed with the FOs from the AC Review.
3. The consensus check on the revised document should use the same question structure as the AC Review itself, to ensure clarity on the responses; and ideally the same system (currently WBS).

Note that prior to Process 2023, [consensus was defined as the lack of a Formal Objection](https://www.w3.org/2021/Process-20211102/#Consensus). We revised this definition for various reasons in Process 2023, and I don't think we should revert; but the ability to block consensus without actually registering an FO leaves these cases in a weird limbo and makes it hard for a Council to properly address the W3C Decision at hand.

**Comment by plehegar** [comment]
Fyi, I'm experimenting with implementing how we assess the consensus check. See [REVIEW by 2024-03-19/20: Proposed changes to the Federated Identity Working Group charter](https://lists.w3.org/Archives/Member/member-charters-review/2024Mar/0007.html)  (Member-only link).

The WBS survey is available to all of the AC Reps, but only the AC Reps who responded to the original WBS survey were notified. No notification was sent to the public. Since the original comments were all supportive of the original proposed charter, the deadline for the new WBS survey is only one week. The proposed changes were discussed with the CG by the way since they were the ones who drafted the charter in the first place.

**Comment by frivoal** [comment]
One thing that I would add is that if the proposed substantive changes would expand the scope, then it need to go back to the whole AC, because some people who didn't cast a ballot might have if the scope had included something they cared about.

**Comment by plehegar** [comment]
I concur that changes in scope should trigger new AC reviews but I'm worried that limiting the set of substantive changes that can be done on charters will add too many tape layers. The recent update of the FedID charter to update the [out-of-scope section](https://github.com/w3c/strategy/issues/427#issuecomment-1973244230) shouldn't trigger an entire new AC review imho. While [adding Digital Credentials](https://github.com/w3c/strategy/issues/427#issuecomment-1973244230) to it was certainly a major change that ought to (and will) trigger a full separate AC review. The case of the WebAppSec charter is a bit murkier since the deliverable was part of the charter submitted to the AC for review but it was noted that the [scope section](https://github.com/w3c/webappsec/issues/646) needed to include it as well.

One alternative here would be not to limit the review of the proposed changes to the set of the AC who provided feedback in the first review. Similar to our technical reports tracks, we should be able to accept comments on charters from anyone at any time.  After that, it's a question of how long we should give the AC for its re-review and I would advocate that it should be context dependent.

**Comment by dwsinger** [comment]
Perhaps the team should make the considered call on whether a new AC Review is needed, and make a 'decision' that could be objected to?

**Comment by TallTed** [comment]
> Perhaps the team should make the considered call on whether a new AC Review is needed, and make a 'decision' that could be objected to?

Presuming the Team would notify the full AC of this Decision with appropriate window for FO, that seems reasonable.

Still, I do wonder whether that would actually save AC time, vs notifying them of the proposed Charter DIFF, with a timeboxed link that would preload their previous vote&comment so they could quickly click to apply the same vote&comment to the revised Charter or _almost_ as quickly revise and submit their previous vote&comment on the revision...

**Comment by dwsinger** [comment]
Yes, I am envisaging that the same email that documents what happened after the AC vote would do that. Something like "The AC vote recorded 7 objections and 3 formal objections, 28 yes and 4 abstains. Two of the FOs were withdrawn after a change was made to the charter; one was ruled against by Council. The objections and the two FOs resulted in changes to the charter, and we are now seeking consensus support from those who 42 who voted. The Team does not believe that these changes are sufficiently substantive to warrant a second full vote at the AC; however, this decision can be objected to."
