### ISSUE TITLE
Inaccurate text about Membership Agreements

### ISSUE THREAD

**Issue by hober** [w3c/process#879]
In the un-numbered section named "Relation of Process Document to Patent Policy and Other Policies," the first sentence reads:

> W3C Members' attention is called to the fact that provisions of the Process Document are binding on Members per the [Membership Agreement](https://www.w3.org/Consortium/Agreement/Member-Agreement) [[MEMBER-AGREEMENT]](https://www.w3.org/2023/Process-20231103/#biblio-member-agreement).

This implies two things, both of which are demonstrably false:

1. That there is one, singular Membership Agreement, when in fact there are (unfortunately) many.
2. That the one, singular Membership Agreement is the linked document.

The (as I said, unfortunate) reality is that there are a number of Membership Agreements. I don't know offhand how many, but "several" is not an incorrect depiction. I also don't know offhand if all of them make the Process Document binding on Members in the way that this text presumes. (I sure hope they do!)

While in the long term it would be best to reduce the number of active Membership Agreements to one, in the short term it would be nice if this text were updated to be accurate. As it stands, a Member representative could click on the above link and think that the resulting document is the one that binds her organization, when it very well may not be.

**Comment by frivoal** [comment]
I suspect a rather simple fix could be to link to https://www.w3.org/membership/agreement/ instead of https://www.w3.org/Consortium/Agreement/Member-Agreement, as that pages talk about the fact that the Membership agreement has changed over the years, and links to all (?) successive version of it.

(And yes, by my read, all versions linked there do make the Process binding.)
