### ISSUE TITLE
Clarify changes allowed during CR->REC transition

### ISSUE THREAD

**Issue by fantasai** [w3c/process#919]
Filing this to make sure we review the text about dropping PR to ensure that the document published as REC corresponds precisely to the document reviewed during the patent exclusion period and AC formal review.

**Comment by nigelmegitt** [comment]
There must be _some_ expected and permitted minor differences, so it would be good to be clear about what they are. I'm thinking of things that you may or may not consider to be part of the document:

* The SOTD must change to reflect the status change from CR to REC
* The document title must change
* ... not sure what else?

Is there scope for requiring specific markup on the AC Review CR, so that the final SOTD text will be visible to reviewers but in a "proposed for Rec" or "for review" styled block, I wonder? I'm not sure if that's a Process question or not.

**Comment by fantasai** [comment]
Currently we only restrict to "must not contain substantive changes" from the PR, so probably we can preserve that qualification. https://www.w3.org/policies/process/#transition-rec
