### ISSUE TITLE
How do I suggest a specification without making a whole draft about it? This specification will save lives.

### ISSUE THREAD

**Issue by upintheairsheep** [w3c/process#947]
Hello, I would like to suggest a protocol to enable non-cellular internet connected devices to receive emergency alerts, see https://en.wikipedia.org/wiki/Wireless_Emergency_Alerts

Today, only cellular devices like smartphones are required to have EAS, and radios and cable TV have as well. Unfortunately, if you do not have a phone nearby, you will not hear the message and potentially risk your life. This is especially important for places like California that receive Earthquakes, which are extremely urgent, seconds matter. There should be a protocol to enable wireless devices such as smart TVs and WiFi-only tablets to receive EAS messages and display them, preferably please make it use as less resources for the deamon as possible, so it does not impact the performance of low-end or antiquated devices, and can fit on small IoT devices, possibly a specific packet can send a request to the device, but it may open up a security hole.

**Comment by frivoal** [comment]
The typical practice is to write what is called an "explainer": a document where you describe the problem you are trying to solve, outline the solution you are proposing without going into full details, discuss what alternatives were considered (if any). At that stage, which we call incubation, there aren't really any formal rules, about how to do things. Your goal is to progressively flesh out your idea, get feedback on it, and gather a community of interested people who would like to work on standardizing it. Eventually, if your idea is gathering enough interest, you may be able to push for the creation of a working group (see https://www.w3.org/policies/process/#group-lifecyle for the current process for starting working groups, or https://www.w3.org/policies/process/drafts/#group-lifecycle for the proposed evolution), but that isn't the first step.

As long as your idea is in incubation, there aren't really rules about how to go about it. You can write your explainer anywhere (personal website, your own github repository…), and seek feedback any way you want. That said, there are some common patterns and gathering places:

* W3C gives the possibility to any group of 5 or more people to create their own "community group" to discuss their ideas. This doesn't grant any status to the ideas you discuss, but it provides a space for discussion, with clarity over the copyright and patent rules applied to things discussed there. see https://www.w3.org/community/.
* The Web Incubator Community Group is one such pre-existing community group, but rather than being focused on a particular topic, it offers a general purpose venue for proposals to be made and discussed. See https://wicg.io/ for a description of how it works

----

With all that said, this repository is not a support forum for questions about how to do things at W3C, but to propose evolution to the rules by which it operates. So your question, while interesting, is out of scope for this group, so I am closing this issue. I hope the answer above was nevertheless helpful.
